language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

git:
  depth: 1

env:
  global:

install:
  - composer install -q -n --no-ansi --no-progress --dev --prefer-dist --no-suggest
  - ./vendor/bin/zephir generate --backend=ZendEngine3

before_script:

script:

notifications:
    email:
        on_success: never
        on_failure: never
