language: php

php:
  - 7.0

git:
  depth: 1

env:
  global:

dependencies:
  cache_directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install -q -n --no-ansi --no-progress --dev --prefer-dist --no-suggest
  - vendor/bin/install-phalcon.sh

install:
  - vendor/bin/zephir generate --backend=ZendEngine3

before_script:

script:

notifications:
    email:
        on_success: never
        on_failure: never
